FROM python:3.8.16-slim

RUN apt update && \
    apt install -y --no-install-recommends \
        curl telnet ncurses-bin \
        locales ffmpeg libsm6 libxext6

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV PYTHONIOENCODING UTF-8

COPY requirements.txt /tmp/
RUN pip install -U pip \
    && pip install --no-cache-dir -r /tmp/requirements.txt

ADD app /code/app
WORKDIR /code

